Front/Controllers/DocsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Front.Controllers
{
    public class DocsController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }

    }
}

Front/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Front.Controllers
{
    public class HomeController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }

        [Route("/bug")]
        public ActionResult BugReport()
        {
            return View();
        }

    }
}

Front/Views/Docs/Index.cshtml
@{
    ViewBag.Title = "Documentation";
}

@section Scripts
{    
    <script src="~/Scripts/Highlight/highlight.pack.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
}

@section Styles
{ 
    <link href="~/Content/Highlight/default.css" rel="stylesheet" />
}

<div id="installation">
    @RenderPage("_Installation.cshtml")
</div>


<div id="code-connection">
    @RenderPage("_Connection.cshtml")
</div>

<div id="code-query">
    @RenderPage("_Quering.cshtml")
</div>

<div id="code-functions">
    @RenderPage("_Functions.cshtml")
</div>

Front/Views/Docs/_Connection.cshtml
<h2 class="doc-head">Connecting to a database</h2>

<p>

    In order to set up a new connection, you will need to create a new instance of <b>Mysql.Simple.Database</b>
    by providing the connection string. Since the <b>Database</b> class allows an implicit operator for the connection
    string, you can directly pass the connection string without a constructor to create a new Database connection.
    The following is an example of a connection string and creating a new insance of a database.
</p>

<pre><code class="cs">
    string ConnectionString = "Server=;Uid=;Database=;password=;SslMode=none";

    Database db = ConnectionString;
</code></pre>

<p>
    However for readability, if needed, there is always the option to use the constructor with the connection 
    as a parameter as follows:
</p>

<pre><code class="cs">
    Database db = new Database(ConnectionString);
</code></pre>

<p>
    The database object contains an object of <b>MySql.Data</b>'s <b>MySqlConnection</b> that has been connected 
    with the connection string. If required, this object can be accessed by the help of an implicit conversion or
    by using the <b>Connection</b> property. The two lines below help fetch the same object in two different ways. 
</p>

<pre><code class="cs">
    MySqlConnection conn1 = db;

    var conn2 = db.Connection;
</code></pre>

<p>
    The database object also implements <b>IDisposable</b>. On dispose, it closes the connection and disposes the
    <b>MySqlConnection</b> object. Hence this object can be created with using to ensure that the connection is 
    closed and the object is disposed.
</p>

<pre><code class="cs">
        using (Database db = ConnectionString)
        {
            
        }
</code></pre>

Front/Views/Docs/_Functions.cshtml
<h2 class="doc-head">Code friendly quering</h2>

<p>
    The database object also has functions to execute code friendly sql. That is instead of adding entire 
    large queries into one string without any syntax lighliting and later looking for the different parts 
    of your sql, there are functions to run almost all kinds of queries to make the sql commmands more readable
    in the code. All these functions can be followed by the four functions mentioned above: Query(), QuerySingle(),
    QueryValue() and Query().
</p>

<h3>Select function</h3>

<pre><code class="cs">

    db.Select("id, fname", "lname")
        .From("user u")
        .Join("entries e", "u.id = e.userID")
        .Where("username LIKE $0", query)
        .Order("fname")
        .Limit(20)
        .Query();


</code></pre>

<p>

    <ul>
        <li>
            <b>Select: </b>
            Select is optional (default *), you can directly start with the second function From.
            You can mention all fields under a string with commas or as multiple strings or both.
        </li>
        <li>
            <b>From: </b>
            From is the only mandatory. Can be used directly from db or continuing from select.
            From can again take multple table names similar to the select function above
        </li>
        <li>
            <b>Join: </b>
            Multiple joins can be chained one after another.
            All four join functions are available.
        </li>
    </ul>

</p>


<h3>Debug functionality</h3>

<p>
    For debugging porpose, a property 'FullQuery' is provided that can be used in place of the four functions. 
    This property provides the exact query that would be executed when the chained functions run. 
</p>

<pre><code class="cs">

    string sql =
    db.Select("id, fname", "lname")
        .From("user u")
        .Join("entries e", "u.id = e.userID")
        .Where("username LIKE $0", query)
        .Order("fname")
        .Limit(20)
        .FullQuery;


</code></pre>

<p>
    Or to reuse the query, the following code such as the following can be used: 
</p>

<pre><code class="cs">

    var q = db.Select("id, fname", "lname")
        .From("user u")
        .Join("entries e", "u.id = e.userID")
        .Where("username LIKE $0", query)
        .Order("fname")
        .Limit(20);

    string sql = q.FullQuery;
    using (var users = q.Query());

</code></pre>


<h3>Advanced Conditions</h3>

<p>
    If the where clause is complex with nested conditions, functionalities for convenient management are provided. 
    These can be used in the where clause inside under the select and update functions.
</p>

<p>First You will need to create the conditions. Creating a condition can be done as follows.</p>

<pre><code class="cs">
    var cond = Conditioner.Build("name LIKE $0", name);  // the usual format with the object(s)
    var cond2 = Conditioner.Build("fname = $0", fname);  // the usual format with the object(s)
    var cond3 = Conditioner.Build("lname", lname);  // with no $ or @@, automatically converts to "lname = 'lame'" if lname were 'lame'
    var cond4 = Conditioner.Build("fname = lname"); // without any object
</code></pre>

<p>To simplify the condition creations, you can take the help of the <b>Conditioner</b> class</p>

<pre><code class="cs">
    Conditioner c = new Conditioner(); // creates a helper object

    // now the same above code can be written with the helper object c
    var cond = c["name LIKE $0", name]; 
    var cond2 = c["fname = $0", fname]; 
    var cond3 = c["id", id];  
    var cond4 = c["fname = lname"];
</code></pre>

<p>Now these conditions can be uses in complex conditional statments as follows</p>

<pre><code class="cs">
    .WhereConditional(cond.And(cond2.Or(cond3).And(Cond4)));
</code></pre>

<p>Or now you can use it as follows</p>

<pre><code class="cs">
    .WhereConditional(cond & (cond2 ! cond3 & Cond4));
</code></pre>

Front/Views/Docs/_Installation.cshtml
<h2 class="doc-head">Installation</h2>

<p>
    Nuget package url: 
        <a target="_blank" href="https://www.nuget.org/packages/MySql.Simple/">https://www.nuget.org/packages/MySql.Simple/</a>
    
    On the package manager console enter:
</p>

<pre><code>Install-Package MySql.Simple
</code></pre>

Front/Views/Docs/_Quering.cshtml
<h2 class="doc-head">Quering</h2>

<p>
    There are four ways (four functions) queries can be excuted. These are similar to those of <b>Webmatrix.Data</b>.
    All four of these function support a syntax that simplifies the usage of <b>String.Format</b> when calling the function.
    So instead of using:
    <code>(String.Format("INSERT INTO User (Username, FirstName) Values ('{0}', '{1}')", Username, Firstname))</code>
    you could simply do:<code>("INSERT INTO User (Username, FirstName) Values ('@@0', '@@1')", Username, Firstname)</code>.
    Note that @@0 and @@1 are @@ followed by the index of the params. So @@0 refers to the param at index 0 which is 'Username'.
    
</p>

<p>The following are the four different ways to execute sqls.</p>

<h3>Simply execute a query (no output)</h3>

To directly execute a query you can simply call the <b>.Execute()</b> method in the <b>Database</b> object. 
This would return an int that specifies the number of rows effected in the database.

<pre><code class="cs">
        int RowsEffected = db.Execute("INSERT INTO Users (Username, FirstName) Values ('@@0', '@@1')", Username, Firstname);
</code></pre>

 <h3>Run query to get a single value output</h3>

<p>
    To get just a single value as an output, use the <b>.QueryValue()</b> method of the <b>Database</b> object.
    This function would return the first column of the first row of the result of the query.
</p>

<pre><code class="cs">

    using (var result = db.QueryValue("SELECT COUNT(ID) FROM Users"){

        // setting to an existing variable with the same datatype
        User user = new User(){
            ID = result;
        };

        // or directly returning assuming the return type is the same as the datatype
        return result;
    }

</code></pre>


 <h3>Run query to get an entire row</h3>


<p>
    To fetch a entire row, use the function <b>.QuerySingle()</b>. This function returns an object of the class <b>MySql.Simple.QueryResult</b>.
    This object contains and uses an object of <b>MySql.Data.MySqlDataReader</b>. Since this object implements disposable, 
    it can be used with using. The dispose function disposes the <b>MySqlDataReader</b> object. Once you fetch the 
    <b>QueryResult</b> object, you can use this object to access columns of the row by the column name or index. 

</p>

<pre><code class="cs">
    using (var result = db.QuerySingle("SELECT * FROM User WHERE ID = @@0", ID))
    {
        
        if (result){ // check if a row was returned. avoid if you are sure the query returns atleast one row
           User user = new User(){
                ID = result["ID"],
                UserName = result["username"],
                FirstName = result["FirstName"],
                LastName = result["LastName"],
                DateOfBirth = result["DateOfBirth"]
            };
        }

        
    }    
</code></pre>

<p>
    In the above code, note that once the value of the column is fetched, when it is being assigned to a variable, it returns 
    in the same type as the variable it is being assigned to. For instance <code>user.ID</code> is an int. 
    So <code>result["ID"]</code> returns an int. Since <code>UserName</code> is a string, <code>result["username"]</code> will also return string.
    Since <code>DateOfBirth</code> is of type DateTime, <code>result["DateOfBirth"]</code> returns DateTime.
    Note that all these assignments directly use implisit operators and the functions of <b>MySqlDataReader</b>, 
    <b>.GetInt32()</b>, <b>.GetString()</b> and <b>.getDateTime()</b> respectively. In other words these operation have no performance issues
    as compared to directly using these functions. These assignments are compatable with every primitive datatypes and with the types 
    <b>MySqlDateTime</b>, <b>MySqlDecimal</b> and <b>MySqlGeometry</b>.
</p>

<p>
     If you require to use the reader object within the result object, you can either use the implicit converter or
    the property <b>reader</b>.The two lines below help fetch the same object in two different ways.
</p>

<pre><code class="cs">
    MySqlDataReader reader1 = result;

    var reader2 = result.reader;
</code></pre>

<h3>Using a query to fetch multiple rows</h3>

<p>
    Fetching multiple rows can be done with the <b>Query()</b> function. The process is very similar to using <b>QuerySingle</b>.
    The main difference between the two is looping. In order to loop the result, the <b>result..Read()</b> function is called 
    which gets each line and returns a boolean (false if empty). 
</p>

<pre><code class="cs">
   using (var result = db.Query("SELECT username, FName, LName FROM tblUsers"))
   {
       while (result.Read())
       {
           users.Add(new TUser() {
              UserName = result["username"],
              FName = result["FName"],
              LName = result["LName"],
              DateOfBirth = result["DateOfBirth"]
           });
       }
   } 
</code></pre>

Front/Views/Docs/_Sample.cshtml
<h2 class="doc-head">Sample code</h2>


<p>
    The following shows the complete code for using this libary fetching a list of users from the 
    database and adding them to a list. Note that the user object is not included in the libary.
    <br />
    For more information on the this code, read below for the full explaination. 
</p>
<pre><code class="cs">
    var Users = new <span class="built_in">List</span>&lt;User&gt;();
    using (Database db = ConnectionString){
        using (var result = 
                db.Select("ID, username, FirstName, LastName, DateOfBirth")
                  .From("Users")
                  .Where("IsActive = $0 AND username LIKE '@@1%' AND FirstName = $2", true, "test", "Test")
                  .Order("LastName")
                  .Limit(15)
                  .Query()
              )
        {
            if (!results){
                // no results
            }
            while (result.Read())
            {
                users.Add(new User() {
                    ID = result["ID"],
                    UserName = result["username"],
                    FirstName = result["FirstName"],
                    LastName = result["LastName"],
                    DateOfBirth = result["DateOfBirth"]
                });
            }
        }
    }
        </code></pre>

Front/Views/Home/BugReport.cshtml
@{
    ViewBag.Title = "Bug Report";
}

<h2>Connecting soon...</h2>

Front/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}


<div class="well">
    <h1>MySql Simple</h1>

    <h3>A simple way to access a <b>MySQL database</b> using <b>.NET Standard</b></h3>

    <div class="buttons row">
            <a class="col-sm-4 btn btn-lg btn-default" target="_blank" href="https://www.nuget.org/packages/MySql.Simple">Go to Nuget page</a>
            <a class="col-sm-4 btn btn-lg btn-default" href="@Url.Action("Index", "Docs")#installation">Installation Instructions</a>
            <a class="col-sm-4 btn btn-lg btn-default" href="@Url.Action("Index", "Docs")#code-connection">Read Documentation</a>
    </div>

</div>


<div id="code-sample">
    @RenderPage("../Docs/_Sample.cshtml")
</div>

Front/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>@ViewBag.Title - MySql Simple</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.lumen.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    @RenderSection("Styles", false)

    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("Scripts", false)

    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <script>
        (adsbygoogle = window.adsbygoogle || []).push({
            google_ad_client: "ca-pub-6080226555483390",
            enable_page_level_ads: true
        });
    </script>

</head>
<body>

    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="@Url.Action("Index", "Home")">MySql Simple</a>
            </div>
            <ul class="nav navbar-nav">
                <li><a href="@Url.Action("Index", "Home")">Home</a></li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="@Url.Action("Index", "Docs")" >Documentation<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="@Url.Action("Index", "Docs")#installation">Installation</a></li>
                        <li><a href="@Url.Action("Index", "Docs")#code-connection">Connect to a database</a></li>
                        <li >
                            <a href="@Url.Action("Index", "Docs")#code-query">Quering</a>
                            @*<ul class="dropdown-menu">
                                <li><a href="@Url.Action("Index", "Docs")#code-query">Run SQL</a></li>
                                <li><a href="@Url.Action("Index", "Docs")#code-query">Fetch value</a></li>
                                <li><a href="@Url.Action("Index", "Docs")#code-query">Fetch row</a></li>
                                <li><a href="@Url.Action("Index", "Docs")#code-query">Fetch multiple rows</a></li>
                            </ul>*@
                        </li>
                        <li><a href="@Url.Action("Index", "Docs")#code-functions">Code friendly Quering</a></li>
                    </ul>
                </li>
                <li><a href="https://www.nuget.org/packages/MySql.Simple/ContactOwners">Contact</a></li>
                <li><a href="https://fb.com/mysql.simple">Facebook</a></li>
            </ul>
        </div>
    </nav>

    <div class="container main-content">
        @RenderBody()
    </div>

</body>
</html>